// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var VerifierContract = artifacts.require('SquareVerifier');
var ProofObject = require('../../zokrates/code/square/proof.json');


// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps
contract('TestSquareVerifier', accounts => {
    const account_one = accounts[0];

    describe('Proof verification', function () {
        beforeEach(async function () {
            this.contract = await VerifierContract.new({
                from: account_one
            });
        });

        it('It should verify this transaction as valid with correct proof and inputs', async function () {
            const isValid = await this.contract.verifyTx(ProofObject.proof.a,ProofObject.proof.b, ProofObject.proof.c ,ProofObject.inputs)
            assert.equal(isValid, true, 'Is not equal');
        });
    });
})
